version: 2.1
orbs:
  sbom-transmitter: manifest/sbom-transmitter@0.2.2
  node: circleci/node@4.7.0

filters: &filters
  tags:
    only: /.*/

jobs:
  sbom:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - sbom-transmitter/install-syft
      - sbom-transmitter/run-syft:
          purl: ./
          file: python-example-sbom.json
      - sbom-transmitter/transmit: 
          sbom-file-path: python-example-sbom.json

  sbom-cdxgen:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: sudo npm install -g @cyclonedx/cdxgen
          name: Install dependencies
      - run:
          command: cdxgen .  -o ./bom.json --deep --type python --resolve-class --recurse
          name: Create SBOM
      - run: 
          command: cat ./bom.json
          name: Install dependencies
      - sbom-transmitter/transmit: 
          sbom-file-path: ./bom.json
          
workflows:
  sbom:
    jobs:
      - sbom:
          filters: *filters
      - sbom-cdxgen:
          filters: *filters
