version: 2.1
orbs:
  sbom: manifest/sbom@0.0.3
  node: circleci/node@5.1.0

filters: &filters
  tags:
    only: /.*/

jobs:
  sbom-syft:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - sbom/install:
          version: v0.10.0
      - sbom/generate:
          format: spdx-json
          source: .
  sbom-cdxgen:
    executor: node/default
    steps:
      - checkout
      - sbom/install:
          generator: cdxgen
          version: v0.10.0
      - sbom/generate:
          args: "--spec-version 1.4"
          format: cyclonedx-json
          generator: cdxgen
          output: bom.json
          source: .
          source_name: node
          source_version: 14.17.0
workflows:
  sbom:
    jobs:
      - sbom-syft:
          filters: *filters
      - sbom-cdxgen:
          filters: *filters
